### ISSUE TITLE
翻訳: /references/keeping-up-with-gutenberg-index/*

### ISSUE THREAD

**Issue by t-hamano** [jawordpressorg/core-handbook#110]
以下のページの翻訳をします。これらのページは、Make WordPress Coreに投稿されたGutenbergに関連する記事のリンク集で、毎年更新されているようです。

更新するのは冒頭・末尾の文章のみで、記事リンクはタイトル含めそのまま残す予定なので、まとめて対応したいと思います。

**翻訳するページのURL**
https://make.wordpress.org/core/handbook/references/keeping-up-with-gutenberg-index/
https://make.wordpress.org/core/handbook/references/keeping-up-with-gutenberg-index/keeping-up-with-gutenberg-index-2020/
https://make.wordpress.org/core/handbook/references/keeping-up-with-gutenberg-index/keeping-up-with-gutenberg-index-2021/
https://make.wordpress.org/core/handbook/references/keeping-up-with-gutenberg-index/keeping-up-with-gutenberg-index-2022/

**翻訳するページのリポジトリ内のパス**
core\references\keeping-up-with-gutenberg-index.md
core\references\keeping-up-with-gutenberg-index\keeping-up-with-gutenberg-index-2020.md
core\references\keeping-up-with-gutenberg-index\keeping-up-with-gutenberg-index-2021.md
core\references\keeping-up-with-gutenberg-index\keeping-up-with-gutenberg-index-2022.md

**原文との差分チェック**

- [x] 原文ページとリポジトリ内の内容が同じものか確認済み（ざっくりで良いです）

**Comment by atachibana** [comment]
これ Birgit さんが始めたんですよね、ありがたいです。
