### ISSUE TITLE
提案: textlintの導入について

### ISSUE THREAD

**Issue by t-hamano** [jawordpressorg/core-handbook#14]
最低限の翻訳ルールを機械的なチェックをかけられないかと調べていた所、[textlint](https://github.com/textlint/textlint) というツールを発見し、[community-handbook](https://github.com/jawordpressorg/community-handbook/blob/master/package.json) にも導入されている事を知りました。

これをコアハンドブックにも導入してはどうでしょうか、というご提案です。

## 概要
- community-handbook と同じ拡張プラグイン、設定 (`.textlintc`)、GitHub Actions を導入する
- PR をもらった時や master にマージされる時に、GitHub Actions が走って、ルールに合致していない箇所が検出される
- リポジトリをローカルに clone して作業している人は、 `npm run lint` を叩く事で手動実行も出来る

## メリット
- 機械的なチェックをかける事で、目視チェックでの漏れを防ぐ事が出来る
- PRをレビューする人の負担が減る

[こちらの issue](https://github.com/jawordpressorg/community-handbook/pull/130) にあるように、規約には沿っているが機械的にエラーになってしまうケースも多いと思うので、これをパスしないとマージ出来ないよといった厳しいものではなく、翻訳の負担を減らすための補助ツールとして導入出来れば良いなと思っています。

**Comment by atachibana** [comment]
はい、いいアイデアと思います。最初から仕掛けておけば後で修正する手間も省けますしね。

**Comment by t-hamano** [comment]
ありがとうございます！
では環境を作ってPRを出してみたいと思います。
