### ISSUE TITLE
翻訳: 

### ISSUE THREAD

**Issue by osamunize** [jawordpressorg/core-handbook#25]
以下のページの翻訳をします。

**翻訳するページのURL**

https://make.wordpress.org/design/handbook/

**翻訳するページのリポジトリ内のパス**

design-handbook/design/

**原文との差分チェック**

- [ ] 原文ページとリポジトリ内の内容が同じものか確認済み（ざっくりで良いです）

**Comment by t-hamano** [comment]
こちらのissueは立て間違いかな？とましたので、クローズさせていただきます。
