### ISSUE TITLE
翻訳: about.md

### ISSUE THREAD

**Issue by osamunize** [jawordpressorg/core-handbook#27]
以下のページの翻訳をします。

**翻訳するページのURL**

https://make.wordpress.org/core/handbook/about/

**翻訳するページのリポジトリ内のパス**

core-handbook/blob/main/core/

**原文との差分チェック**

- [x] 原文ページとリポジトリ内の内容が同じものか確認済み（ざっくりで良いです）

**Comment by osamunize** [comment]
@t-hamano さん
すみません、プルリクエストを送ろうとしたところ
[jawordpressorg/core-handbook] PR run failed: textlint - 翻訳: about.md #27 (9ee4e66)
というエラーになって処理できていないようです。（やり直してみましたが同様でした）
ログを見てもいまひとつわからないのですが、なにかお分かりになりますでしょうか。

https://github.com/jawordpressorg/core-handbook/actions/runs/2684429805

**Comment by t-hamano** [comment]
説明不足ですみません！
GitHub上で、自動的に翻訳ルールに合っているかチェックする仕組みを入れているのですが、何せ機械的なチェックしか出来ないので、どうしてもエラーが発生しています。
エラーが発生してもプルリクエストはちゃんと送られていますので、気にされないでください 😆

**Comment by t-hamano** [comment]
※ issue #27 の対応PRです。

**Comment by osamunize** [comment]
ありがとうございます！承知しました！
