### ISSUE TITLE
原文にGlossaryの文章が含まれている

### ISSUE THREAD

**Issue by miminari** [jawordpressorg/core-handbook#44]
例: https://github.com/jawordpressorg/core-handbook/blob/en/core/contribute/git.md

[wp-handbook-converter](https://github.com/mirucon/wp-handbook-converter)でのトリムが効かなくなっているので調査、対応する

その他、不要な箇所にエスケープ処理が入っているのでturndownの設定などを変更する必要もありそう

**Comment by t-hamano** [comment]
[こちらのコメント](https://github.com/jawordpressorg/core-handbook/pull/28#discussion_r922769897)に書いた通り自分も気になっていまして、翻訳する時にトリムすれば良いものなのかなと思ってたのですが、本来はコンバータ通した時点でトリムされるということですよね 🤔

**Comment by miminari** [comment]
@t-hamano https://github.com/mirucon/wp-handbook-converter/pull/22
で私がやっつけで対応した部分なのですが、多分、仕様が変わっちゃってると思われます。

**Comment by t-hamano** [comment]
了解しました！
自分も調べてみます😀

**Comment by miminari** [comment]
@t-hamano あ、やられます？じゃあお任せしようかな。

**Comment by t-hamano** [comment]
やりますよー👍
「不要な箇所のエスケープ処理」というのはどの辺りの箇所ですか？

**Comment by miminari** [comment]
@t-hamano 上のリンクしてるPRの部分ですー！
cli.jsの92行目あたり

**Comment by t-hamano** [comment]
@miminari 

[Wayback Machine](https://archive.org/web/)を使って2～3年前のソースと比較してみたのですが、glossary周りのタグ構造は変わってないので、おそらく `strong` タグで囲まれた場合にトリムできていないのかな？と思います。
（通常の本文内のglossaryはちゃんとトリムされてるっぽいです）
ちょっとそのあたりを調べてみます。

> @t-hamano 上でリンクしてるPRの部分ですー！
> cli.jsの92行目あたり

マークダウンに変換されるときに、不要な「\」が追加されてるという意味かと思ったのですが、合ってますか？
例えばこういう箇所です

![slash](https://user-images.githubusercontent.com/54422211/180608999-8b840241-b0e7-499e-8f02-7539f89c1856.png)

もしここの箇所の事であれば、バックスラッシュのエスケープ処理なので問題無いのかなと思っています

**Comment by miminari** [comment]
@t-hamano ありがとうございますー。そうだと思います、たぶん、例外処理がうまく出来てない気配。

> 不要な箇所のエスケープ処理
の話でしたね、すみません、勘違いしてました。
coreの方にはもしかしたら該当箇所がないかもしれない（ただのエスケープ処理で問題ない）のですが、
プラグインハンドブックのほうで以下のページのように、preタグ内での処理がちょっとおかしいんですよね。
https://github.com/jawordpressorg/plugin-handbook/blob/main/plugins/schema.md

**Comment by t-hamano** [comment]
@miminari 
了解しました！
そのあたりを調査してPR送ってみますね。

**Comment by t-hamano** [comment]
## 対応メモ

[wp-handbook-converter](https://github.com/mirucon/wp-handbook-converter)のマークダウン変換処理について、以下を修正したPRを送る

- [ ] glossaryが一部除去出来ていない。（おそらく、`strong`タグで囲まれた部分）
- [ ] `pre`タグが除去され、コード例が正しく表示されない。`pre`タグ → 「```」 に変換すべき？
- [ ] `pre`タグのコード例の中で、記号（`*_[]` ）の前に不要なバッククオートが入る。

**Comment by miminari** [comment]
@t-hamano ありがとうございますー。
調査途中なのですが、たぶん、glossary以外の対応については、turndown側のaddRuleオプションをイジってあげると出来るような気もします。

https://wpja.slack.com/archives/CRF0HNDS8/p1657961184616529?thread_ts=1657960534.879619&cid=CRF0HNDS8

**Comment by t-hamano** [comment]
@miminari 
とりいそぎ、ローカルで手を加えたwp-handbook-converterを使って、コアハンドブックとプラグインハンドブックをアップデートしてました。
差分を比較するためのダミーPRを作成しましたので、よろしければプラグインハンドブックの方で、こんな風に変わるよ～というのをお手すきの際に見ていただければ助かります🙏
（コアハンドブックの方は自分でチェックしてみます）

- #45
- https://github.com/jawordpressorg/plugin-handbook/pull/7

**Comment by t-hamano** [comment]
ハンドブックをより適切にパースするために、[wp-handbook-converter](https://github.com/mirucon/wp-handbook-converter) について以下の対応を行った

t-hamano / [wp-handbook-converter/cli.js](https://github.com/t-hamano/wp-handbook-converter/blob/master/cli.js)

- 一部glossaryが除去出来ていなかった点を改善
- `dt`タグを`srong`タグに変換（dtタグはマークダウンでは使えないため、`strong`タグで代用する）
- コードに該当する箇所を、「```」を使ってマークダウンに変換する
  - コード内のエスケープ文字をアンエスケープ
  - クラス名から言語を読み取り、マークダウンにもその言語を付与する（例：```php）
  - 一部不正なpタグがどうしても除去出来なかったので、翻訳時に削除する必要があるかも？
- テーブルタグのサポート（`thead`が無いテーブルは、[この問題](https://github.com/mixmark-io/turndown-plugin-gfm/pull/10)によりHTMLのままマークダウンファイルにも反映されてしまう）
- CLIの引数 `team` を 必須から任意に変更（ここが必須だと、正しいエンドポイントを指定出来ないハンドブックが存在したため）

**Comment by miminari** [comment]
@t-hamano 対応ありがとうございますー！
良い感じかと！Turndown、クラス名でフィルタリング出来るんですね。お利口さんだー。

**Comment by t-hamano** [comment]
@miminari 
ありがとうございます！
コードマークダウンの言語については、パースしたpreタグに言語を表すクラス名が入っていたので、それを ``` の後に付与するようにしてみました。
https://github.com/t-hamano/wp-handbook-converter/blob/d23c4372be2c45e4c0af5085af7e1c9d39035fba/cli.js#L95-L101

では、一度 [wp-handbook-converter](https://github.com/mirucon/wp-handbook-converter) の方にPR送ってみますね😊

**Comment by t-hamano** [comment]
PR: https://github.com/mirucon/wp-handbook-converter/pull/43

**Comment by t-hamano** [comment]
@miminari 
PRがマージされ、npmパッケージも公開いただきましたので、

- en ブランチの更新
- master ブランチへマージ

が終わり次第、このissueはクローズしますね 😄

**Comment by t-hamano** [comment]
#56 にて対応完了
