### ISSUE TITLE
翻訳: /core-handbook/edit/main/core/about/philosophies.md

### ISSUE THREAD

**Issue by imiyake** [jawordpressorg/core-handbook#77]
以下のページの翻訳をします。

**翻訳するページのURL**

https://wordpress.org/about/philosophy/

**翻訳するページのリポジトリ内のパス**

/core-handbook/edit/main/core/about/philosophies.md

**原文との差分チェック**

- [ ] 原文ページとリポジトリ内の内容が同じものか確認済み（ざっくりで良いです）

**Comment by t-hamano** [comment]
#71との重複の為クローズします。
