### ISSUE TITLE
翻訳: /core/references/phpunit-compatibility-and-wordpress-versions.md

### ISSUE THREAD

**Issue by east-or-est** [jawordpressorg/core-handbook#95]
以下のページの翻訳をします。

**翻訳するページのURL**

https://make.wordpress.org/core/handbook/references/phpunit-compatibility-and-wordpress-versions/

**翻訳するページのリポジトリ内のパス**

/core-handbook/blob/main/core/references/phpunit-compatibility-and-wordpress-versions.md

**原文との差分チェック**

- [x] 原文ページとリポジトリ内の内容が同じものか確認済み（ざっくりで良いです）

**Comment by t-hamano** [comment]
ご協力ありがとうございます！

こちらのページですが、既に #70 でご対応いただいているかと思います。
よろしければ、[日本語翻訳プロジェクト Tracking Issue](https://github.com/jawordpressorg/core-handbook/issues/6) をご覧いただき、

チェックが付いていないページ、かつページ名の右側に何も表示されていないもの（アイコン付きのリンクがあるものは、既にアサイン済or対応中のため）

の中から選んでいただければ助かります🙏

**Comment by east-or-est** [comment]
ご確認ありがとうございます！
すみません、翻訳するページのURLをこちらの手違いで違うリンクを貼り付けておりましたので、正しいURLに修正しました。

ものすごく細かい違いなのですが、以前の#70 は「***PHP*** Compatibility and WordPress Versions 」で、今回の「***PHPUnit*** Compatibility and WordPress Versions 」は前回と異なるページになります。

上記でお間違いなければ、このissueを立てたまま翻訳を進められればと思いますが、いかがでしょうか？

**Comment by t-hamano** [comment]
失礼しました！
それでは、ご対応お願いいたします🙏

**Comment by t-hamano** [comment]
@east-or-est さん

こちら、もしご対応が難しそうでしたらこちらで引き継ぎます 👍

**Comment by east-or-est** [comment]
@t-hamano 

確認が遅くなってしまいすみません、こちら失念しておりました。
ありがとうございます！　以前の内容を確認したところ修正箇所は少しだけですので、今からこちらで対応いたします！

**Comment by t-hamano** [comment]
ありがとうございます！なお原文が更新されてまして、テーブルにPHP8.1やWP6.3が追加されていたりしますので、フォーク↓ブランチを一旦更新していただければと思います🙇

**Comment by east-or-est** [comment]
@t-hamano 

ありがとうございます！　先ほどプルリクエストさせていただきました！
原文の方の対応と、テーブルについての補足もありますので、ご確認をお願い致します🙇‍♀️
